server:
  port: 8080

spring:
  main:
    allow-bean-definition-overriding: true

  webflux:
    cors:
      allowed-origins: "http://localhost:4200"
      allowed-methods: "GET,POST,PUT,DELETE"
      allowed-headers: "*"
      allow-credentials: true
